# .github/workflows/terraform-cicd.yml

name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Or your desired deployment branch

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production  # Or the environment you want to deploy to (e.g., staging)

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.1  # Specify the Terraform version (e.g., 1.3.0)

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        continue-on-error: true # If you want to continue even if the plan fails (for logging purposes)

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get ALB DNS Name
        id: get-alb-dns-name
        run: echo "ALB_DNS_NAME=$(terraform output -json alb_dns_name | jq -r '.value')" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

      - name: Set ALB DNS Name Secret in Website Repo
        run: gh secret set ALB_DNS_NAME -b"${{ env.ALB_DNS_NAME }}" -R fredritchie/static_3_tier